version: "3.9"
services:
  db:
    restart: always # always for production
    image: postgres:latest
    container_name: crawler-db
    environment:
      - POSTGRES_PASSWORD=password # change PW here
    volumes:
      - /srv/docker/crawler/data:/var/lib/postgresql/data

  crawler:
    restart: always
    build: .
    container_name: crawler
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PASS=password # change PW here
